"""phase 3 payroll database

Revision ID: 6e450757ae5b
Revises: df96a5dec463
Create Date: 2026-09-05 15:47:56.431714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e450757ae5b'
down_revision: Union[str, Sequence[str], None] = 'df96a5dec463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('calculation_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name='chk_salary_rules_amount_non_negative'),
    sa.CheckConstraint('percentage IS NULL OR percentage >= 0', name='chk_salary_rules_percentage_non_negative'),
    sa.CheckConstraint('sequence >= 0', name='chk_salary_rules_sequence_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('salary_structures',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('salary_structure_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('salary_structure_id', sa.BigInteger(), nullable=False),
    sa.Column('salary_rule_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sequence >= 0', name='chk_salary_structure_rules_sequence_non_negative'),
    sa.ForeignKeyConstraint(['salary_rule_id'], ['salary_rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salary_structure_id', 'salary_rule_id', name='uq_salary_structure_rule')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('payruns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('salary_structure_id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name='chk_payruns_period_end_ge_start'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payruns_created_by_user_id'), 'payruns', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_payruns_period_end'), 'payruns', ['period_end'], unique=False)
    op.create_index(op.f('ix_payruns_period_start'), 'payruns', ['period_start'], unique=False)
    op.create_index(op.f('ix_payruns_salary_structure_id'), 'payruns', ['salary_structure_id'], unique=False)
    op.create_index(op.f('ix_payruns_status'), 'payruns', ['status'], unique=False)
    op.create_table('payrun_employees',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payrun_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('selection_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payrun_id', 'employee_id', name='uq_payrun_employee')
    )
    op.create_index(op.f('ix_payrun_employees_employee_id'), 'payrun_employees', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payrun_employees_payrun_id'), 'payrun_employees', ['payrun_id'], unique=False)
    op.create_index(op.f('ix_payrun_employees_selection_status'), 'payrun_employees', ['selection_status'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payrun_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('payrun_employee_id', sa.BigInteger(), nullable=False),
    sa.Column('salary_structure_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('worked_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('basic_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deduction_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contribution_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('pdf_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('basic_amount >= 0', name='chk_payslips_basic_non_negative'),
    sa.CheckConstraint('contribution_amount >= 0', name='chk_payslips_contribution_non_negative'),
    sa.CheckConstraint('deduction_amount >= 0', name='chk_payslips_deduction_non_negative'),
    sa.CheckConstraint('gross_amount >= 0', name='chk_payslips_gross_non_negative'),
    sa.CheckConstraint('net_amount >= 0', name='chk_payslips_net_non_negative'),
    sa.CheckConstraint('period_end >= period_start', name='chk_payslips_period_end_ge_start'),
    sa.CheckConstraint('worked_days >= 0', name='chk_payslips_worked_days_non_negative'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payrun_employee_id'], ['payrun_employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payrun_employee_id')
    )
    op.create_index(op.f('ix_payslips_contract_id'), 'payslips', ['contract_id'], unique=False)
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_payrun_id'), 'payslips', ['payrun_id'], unique=False)
    op.create_index(op.f('ix_payslips_period_end'), 'payslips', ['period_end'], unique=False)
    op.create_index(op.f('ix_payslips_period_start'), 'payslips', ['period_start'], unique=False)
    op.create_index(op.f('ix_payslips_salary_structure_id'), 'payslips', ['salary_structure_id'], unique=False)
    op.create_index(op.f('ix_payslips_status'), 'payslips', ['status'], unique=False)
    op.create_table('payroll_warnings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payrun_id', sa.BigInteger(), nullable=False),
    sa.Column('payslip_id', sa.BigInteger(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('warning_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_warnings_employee_id'), 'payroll_warnings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_warnings_is_resolved'), 'payroll_warnings', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_payroll_warnings_payrun_id'), 'payroll_warnings', ['payrun_id'], unique=False)
    op.create_index(op.f('ix_payroll_warnings_payslip_id'), 'payroll_warnings', ['payslip_id'], unique=False)
    op.create_index(op.f('ix_payroll_warnings_severity'), 'payroll_warnings', ['severity'], unique=False)
    op.create_index(op.f('ix_payroll_warnings_warning_type'), 'payroll_warnings', ['warning_type'], unique=False)
    op.create_table('payslip_lines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payslip_id', sa.BigInteger(), nullable=False),
    sa.Column('salary_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('calculation_type', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('formula_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='chk_payslip_lines_amount_non_negative'),
    sa.CheckConstraint('base_amount >= 0', name='chk_payslip_lines_base_amount_non_negative'),
    sa.CheckConstraint('quantity >= 0', name='chk_payslip_lines_quantity_non_negative'),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salary_rule_id'], ['salary_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslip_lines_category'), 'payslip_lines', ['category'], unique=False)
    op.create_index(op.f('ix_payslip_lines_payslip_id'), 'payslip_lines', ['payslip_id'], unique=False)
    op.create_index(op.f('ix_payslip_lines_salary_rule_id'), 'payslip_lines', ['salary_rule_id'], unique=False)
    op.create_index(op.f('ix_payslip_lines_sequence'), 'payslip_lines', ['sequence'], unique=False)
    op.add_column('contracts', sa.Column('salary_structure_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_contracts_salary_structure_id'), 'contracts', ['salary_structure_id'], unique=False)
    op.create_foreign_key('fk_contracts_salary_structure_id_salary_structures', 'contracts', 'salary_structures', ['salary_structure_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_contracts_salary_structure_id_salary_structures', 'contracts', type_='foreignkey')
    op.drop_index(op.f('ix_contracts_salary_structure_id'), table_name='contracts')
    op.drop_column('contracts', 'salary_structure_id')
    op.drop_index(op.f('ix_payslip_lines_sequence'), table_name='payslip_lines')
    op.drop_index(op.f('ix_payslip_lines_salary_rule_id'), table_name='payslip_lines')
    op.drop_index(op.f('ix_payslip_lines_payslip_id'), table_name='payslip_lines')
    op.drop_index(op.f('ix_payslip_lines_category'), table_name='payslip_lines')
    op.drop_table('payslip_lines')
    op.drop_index(op.f('ix_payroll_warnings_warning_type'), table_name='payroll_warnings')
    op.drop_index(op.f('ix_payroll_warnings_severity'), table_name='payroll_warnings')
    op.drop_index(op.f('ix_payroll_warnings_payslip_id'), table_name='payroll_warnings')
    op.drop_index(op.f('ix_payroll_warnings_payrun_id'), table_name='payroll_warnings')
    op.drop_index(op.f('ix_payroll_warnings_is_resolved'), table_name='payroll_warnings')
    op.drop_index(op.f('ix_payroll_warnings_employee_id'), table_name='payroll_warnings')
    op.drop_table('payroll_warnings')
    op.drop_index(op.f('ix_payslips_status'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_salary_structure_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_period_start'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_period_end'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_payrun_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_contract_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_payrun_employees_selection_status'), table_name='payrun_employees')
    op.drop_index(op.f('ix_payrun_employees_payrun_id'), table_name='payrun_employees')
    op.drop_index(op.f('ix_payrun_employees_employee_id'), table_name='payrun_employees')
    op.drop_table('payrun_employees')
    op.drop_index(op.f('ix_payruns_status'), table_name='payruns')
    op.drop_index(op.f('ix_payruns_salary_structure_id'), table_name='payruns')
    op.drop_index(op.f('ix_payruns_period_start'), table_name='payruns')
    op.drop_index(op.f('ix_payruns_period_end'), table_name='payruns')
    op.drop_index(op.f('ix_payruns_created_by_user_id'), table_name='payruns')
    op.drop_table('payruns')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('salary_structure_rules')
    op.drop_table('salary_structures')
    op.drop_table('salary_rules')
    # ### end Alembic commands ###
