"""phase 2 attendance and time off

Revision ID: df96a5dec463
Revises: 0d962fb6c859
Create Date: 2026-09-05 15:34:25.309640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df96a5dec463'
down_revision: Union[str, Sequence[str], None] = '0d962fb6c859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_off_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('allocation_required', sa.Boolean(), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('payroll_integration', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('check_out IS NULL OR check_out >= check_in', name='chk_attendance_checkout_after_checkin'),
    sa.CheckConstraint('worked_hours IS NULL OR worked_hours >= 0', name='chk_attendance_worked_hours_non_negative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_check_in'), 'attendance', ['check_in'], unique=False)
    op.create_index('ix_attendance_employee_checkin', 'attendance', ['employee_id', 'check_in'], unique=False)
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_status'), 'attendance', ['status'], unique=False)
    op.create_table('time_off_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('time_off_type_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('taken_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocated_amount >= 0', name='chk_allocations_allocated_non_negative'),
    sa.CheckConstraint('end_date >= start_date', name='chk_allocations_end_date_ge_start'),
    sa.CheckConstraint('taken_amount <= allocated_amount', name='chk_allocations_taken_le_allocated'),
    sa.CheckConstraint('taken_amount >= 0', name='chk_allocations_taken_non_negative'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['time_off_type_id'], ['time_off_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_off_allocations_employee_id'), 'time_off_allocations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_time_off_allocations_end_date'), 'time_off_allocations', ['end_date'], unique=False)
    op.create_index(op.f('ix_time_off_allocations_start_date'), 'time_off_allocations', ['start_date'], unique=False)
    op.create_index(op.f('ix_time_off_allocations_status'), 'time_off_allocations', ['status'], unique=False)
    op.create_index(op.f('ix_time_off_allocations_time_off_type_id'), 'time_off_allocations', ['time_off_type_id'], unique=False)
    op.create_table('attendance_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('corrected_by_user_id', sa.Integer(), nullable=False),
    sa.Column('old_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('old_check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_corrections_attendance_id'), 'attendance_corrections', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_corrected_by_user_id'), 'attendance_corrections', ['corrected_by_user_id'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_created_at'), 'attendance_corrections', ['created_at'], unique=False)
    op.create_table('time_off_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('time_off_type_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refusal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='chk_requests_end_date_ge_start'),
    sa.CheckConstraint('requested_amount > 0', name='chk_requests_requested_amount_positive'),
    sa.ForeignKeyConstraint(['allocation_id'], ['time_off_allocations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['time_off_type_id'], ['time_off_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_off_requests_allocation_id'), 'time_off_requests', ['allocation_id'], unique=False)
    op.create_index(op.f('ix_time_off_requests_employee_id'), 'time_off_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_time_off_requests_end_date'), 'time_off_requests', ['end_date'], unique=False)
    op.create_index(op.f('ix_time_off_requests_start_date'), 'time_off_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_time_off_requests_status'), 'time_off_requests', ['status'], unique=False)
    op.create_index(op.f('ix_time_off_requests_time_off_type_id'), 'time_off_requests', ['time_off_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_off_requests_time_off_type_id'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_status'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_start_date'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_end_date'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_employee_id'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_allocation_id'), table_name='time_off_requests')
    op.drop_table('time_off_requests')
    op.drop_index(op.f('ix_attendance_corrections_created_at'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_corrected_by_user_id'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_attendance_id'), table_name='attendance_corrections')
    op.drop_table('attendance_corrections')
    op.drop_index(op.f('ix_time_off_allocations_time_off_type_id'), table_name='time_off_allocations')
    op.drop_index(op.f('ix_time_off_allocations_status'), table_name='time_off_allocations')
    op.drop_index(op.f('ix_time_off_allocations_start_date'), table_name='time_off_allocations')
    op.drop_index(op.f('ix_time_off_allocations_end_date'), table_name='time_off_allocations')
    op.drop_index(op.f('ix_time_off_allocations_employee_id'), table_name='time_off_allocations')
    op.drop_table('time_off_allocations')
    op.drop_index(op.f('ix_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_index('ix_attendance_employee_checkin', table_name='attendance')
    op.drop_index(op.f('ix_attendance_check_in'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_table('time_off_types')
    # ### end Alembic commands ###
